---# Don't Change #---
DELTAX = {}

---# Vesion #---
DELTAX.Version = 1.8


DELTAX.Licencekey = "DELTA-X_QPZSPWMCYSZRUVMLY"

---# PERMS #--
DELTAX.Bypass = {"deltaxsuperadmin", "deltaxadmin","deltaxmod"}
DELTAX.OpenMenuAllowed = {"deltaxsuperadmin", "deltaxadmin","deltaxmod"}
DELTAX.SpectateAllowed = {"deltaxsuperadmin", "deltaxadmin","deltaxmod"}
DELTAX.ClearAreaAllowed = {"deltaxsuperadmin", "deltaxadmin","deltaxmod"}

---# Ban Message #---
DELTAX.banmessage = "Du wurdest vom Delta-X Anticheat gebannt. Sollte es sich um einen Fehlban handeln, komme bitte in den Support"

---# Webhooks #---
DELTAX.connectWebhook = "https://discord.com/api/webhooks/899700107002392586/ts8O_gjMCY4obBAgCwOGq5fiEtw5WrS-Z_nwFq4tJlRK-FZichWPVeHIgsQz9dNd0x9_"
DELTAX.generalWebhook = "https://discord.com/api/webhooks/899700192822034432/WRdVtguSm6vPlbZG34ydRPgsHvUI-Y-iwQI4NI-1IrbR8m-C72Ck_uto37T4GNY0Luro"
DELTAX.explosionWebhook = "https://discord.com/api/webhooks/899700252465066035/0M9QNUMLbiVbX1_nzLgZjWpfpEnZONPfWA5XLj8bP8lu0yKJ4HxiObDFAxOCqNmxGl-7"
DELTAX.screenshot = "https://discord.com/api/webhooks/900115441089904690/KPaWW0hEmSj_0ng4bV9UBucwXyJcHc4wfNUCeKE8FV_pw_CXYA4nDwHiMLcrGEo7w6GN"

---# Anti Explsoion #---
DELTAX.AntiExplosions = true

DELTAX.AntiInvisibleExplosion = true --detect if cheater spawn an invisible explosion
DELTAX.AntiSilentExplosion = true --detect if cheater spawn an silent explosion


---# Require Steam to Connect #---
DELTAX.requireSteam = true
DELTAX.requireSteamMessage = "Bitte starte Steam, um auf dem Server zu spielen.!"

---# Delta-X AI #---
DELTAX.DeltaXAI = true
DELTAX.OCRKey = "68e7fb469888957" --get your key here http://eepurl.com/bOLOcf

---# Anti Give Weapons #---
DELTAX.antigiveweapons = true

---# Anti Remove Weapons #---
DELTAX.antiremoveweapons = true

---# Anti Remove All Weapons #---
DELTAX.antiremoveallweapons = true

---# Anti kick people from Vehicle #---
DELTAX.anticlearpedtasks = false 

---# Anti Use Blacklist Weapons #---
DELTAXC.AntiUseBlackListWeapon = true

---# Anti Blacklist Message #---
DELTAX.BlacklistedChatMessages = true
DELTAX.BlacklistedChatTable = {
    "nigger", "n1gger", "<script", "d0pamine.xyz", "discord.gg/8888", "8888", "discord.gg/fjBp55t", "moderator", "eulencheats", "lynxmenu", "atgmenu", "hacker", "bastard", "hamhaxia", "333gang", "ukrp", "eguk", "n1gger", "n1ga", "nigga", "n1gga", "nigg3r",
    "nig3r", "shagged", "4dm1n", "4dmin", "m0d3r4t0r", "n199er", "n1993r", "rustchance.com", "rustchance", "hellcase.com", "hellcase", "youtube.com", "youtu.be", "youtube", "twitch.tv", "twitch", "anticheat.gg", "anticheat", "fucking", "ψ", "@", "{", "}", ";", "ϟ", "♕", "Æ", "Œ", "‰", "™", "š", "œ", "Ÿ", "µ", "ß",
    "±", "¦", "»", "«", "¼", "½", "¾", "¬", "¿", "Ñ", "®", "©", "²", "·", "•", "°", "þ", "ベ", "ル", "ろ", "ぬ", "ふ", "う", "え", "お", "や", "ゆ", "よ", "わ", "ほ", "へ", "た", "て", "い", "す", "か", "ん", "な", "に", "ら", "ぜ", "む",
    "ち", "と", "し", "は", "き", "く", "ま", "の", "り", "れ", "け", "む", "つ", "さ", "そ", "ひ", "こ", "み", "も", "ね", "る", "め", "ロ", "ヌ", "フ", "ア", "ウ", "エ", "オ", "ヤ", "ユ", "ヨ", "ワ", "ホ", "ヘ", "タ", "テ", "イ", "ス", "カ", "ン",
    "ナ", "ニ", "ラ", "セ", "ム", "チ", "ト", "シ", "ハ", "キ", "ク", "マ", "ノ", "リ", "レ", "ケ", "ム", "ツ", "サ", "ソ", "ヒ", "コ", "ミ", "モ", "ネ", "ル", "メ", "✪", "Ä", "ƒ", "Ã", "¢", "†", "€", "웃", "и", "】", "【", "j4p.pl", "ֆ", "ȶ",
    "你", "好", "爱", "幸", "福", "猫", "狗", "微", "笑", "中", "安", "東", "尼", "杰", "诶", "西", "开", "陈", "瑞", "华", "馬", "塞", "洛", "ダ", "仇", "觉", "感", "衣", "德", "曼", "L͙", "a͙", "l͙", "ľ̶̚͝", "Ḩ̷̤͚̤͑͂̎̎͆", "a̸̢͉̠͎͒͌͐̑̇", "♚", "я", "Ʒ", "Ӂ̴", "Ƹ̴", "≋",
    "API-AC", "civilgamers.com", "civilgamers", "csgoempire.com", "csgoempire", "g4skins.com", "g4skins", "gameodds.gg", "duckfuck.com", "crysishosting.com", "crysishosting", "key-drop.com", "key-drop.pl", "skinhub.com", "skinhub", "`", "¤", "¡",
    "casedrop.eu", "casedrop", "cs.money", "rustypot.com", "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â", "✈", "⛧", "☭", "☣", "✠", "dkb.xss.ht", "( . )( . )", "⚆", "╮", "╭", "rampage.lt", "xcasecsgo.com", "xcasecsgo", "csgocases.com",
    "csgocases", "K9GrillzUK.co.uk", "moat.gg", "princevidz.com", "princevidz", "pvpro.com", "Pvpro", "ez.krimes.ro", "loot.farm", "arma3fisherslife.net", "arma3fisherslife", "egamers.io", "ifn.gg", "key-drop", "sups.gg", "tradeit.gg",
    "§", "csgotraders.net", "csgotraders", "Σ", "Ξ", "hurtfun.com", "hurtfun", "gamekit.com", "¥", "t.tv", "yandex.ru", "yandex", "csgofly.com", "csgofly", "pornhub.com", "pornhub", "一", "", "Ｊ", "◢", "◤", "⋡", "℟", "ᴮ", "ᴼ", "ᴛᴇᴀᴍ",
    "cs.deals","twat", "STRESS.PW", "mod menu"
}

---# Anti Blacklist Steam Name #---
DELTAX.BlacklistedNames = true 
DELTAX.BlacklistedNamesList = {
    "administrator", "<script", "admin", "adm1n", "discord.gg/8888", "8888","adm!n", "admln", "moderator", "owner", "nigger", "n1gger", "moderator", "eulencheats", "lynxmenu", "atgmenu", "hacker", "bastard", "hamhaxia", "333gang", "ukrp", "eguk", "n1gger", "n1ga", "nigga", "n1gga", "nigg3r",
    "nig3r", "shagged", "4dm1n", "4dmin", "m0d3r4t0r", "n199er", "n1993r", "rustchance.com", "rustchance", "hellcase.com", "hellcase", "youtube.com", "youtu.be", "youtube", "twitch.tv", "twitch", "anticheat.gg", "anticheat", "fucking", "ψ", "@", "&", "{", "}", ";", "ϟ", "♕", "Æ", "Œ", "‰", "™", "š", "œ", "Ÿ", "µ", "ß",
    "±", "¦", "»", "«", "¼", "½", "¾", "¬", "¿", "Ñ", "®", "©", "²", "·", "•", "°", "þ", "ベ", "ル", "ろ", "ぬ", "ふ", "う", "え", "お", "や", "ゆ", "よ", "わ", "ほ", "へ", "た", "て", "い", "す", "か", "ん", "な", "に", "ら", "ぜ", "む",
    "ち", "と", "し", "は", "き", "く", "ま", "の", "り", "れ", "け", "む", "つ", "さ", "そ", "ひ", "こ", "み", "も", "ね", "る", "め", "ロ", "ヌ", "フ", "ア", "ウ", "エ", "オ", "ヤ", "ユ", "ヨ", "ワ", "ホ", "ヘ", "タ", "テ", "イ", "ス", "カ", "ン",
    "ナ", "ニ", "ラ", "セ", "ム", "チ", "ト", "シ", "ハ", "キ", "ク", "マ", "ノ", "リ", "レ", "ケ", "ム", "ツ", "サ", "ソ", "ヒ", "コ", "ミ", "モ", "ネ", "ル", "メ", "✪", "Ä", "ƒ", "Ã", "¢", "?", "†", "€", "웃", "и", "】", "【", "j4p.pl", "ֆ", "ȶ",
    "你", "好", "爱", "幸", "福", "猫", "狗", "微", "笑", "中", "安", "東", "尼", "杰", "诶", "西", "开", "陈", "瑞", "华", "馬", "塞", "洛", "ダ", "仇", "觉", "感", "衣", "德", "曼", "L͙", "a͙", "l͙", "ľ̶̚͝", "Ḩ̷̤͚̤͑͂̎̎͆", "a̸̢͉̠͎͒͌͐̑̇", "♚", "я", "Ʒ", "Ӂ̴", "Ƹ̴", "≋",
    "API-AC", "civilgamers.com", "civilgamers", "csgoempire.com", "csgoempire", "g4skins.com", "g4skins", "gameodds.gg", "duckfuck.com", "crysishosting.com", "crysishosting", "key-drop.com", "key-drop.pl", "skinhub.com", "skinhub", "`", "¤", "¡",
    "casedrop.eu", "casedrop", "cs.money", "rustypot.com", "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â", "✈", "⛧", "☭", "☣", "✠", "dkb.xss.ht", "( . )( . )", "⚆", "╮", "╭", "rampage.lt", "?", "xcasecsgo.com", "xcasecsgo", "csgocases.com",
    "csgocases", "K9GrillzUK.co.uk", "moat.gg", "princevidz.com", "princevidz", "pvpro.com", "Pvpro", "ez.krimes.ro", "loot.farm", "arma3fisherslife.net", "arma3fisherslife", "egamers.io", "ifn.gg", "key-drop", "sups.gg", "tradeit.gg",
    "§", "csgotraders.net", "csgotraders", "Σ", "Ξ", "hurtfun.com", "hurtfun", "gamekit.com", "¥", "t.tv", "yandex.ru", "yandex", "csgofly.com", "csgofly", "pornhub.com", "pornhub", "一", "", "Ｊ", "◢", "◤", "⋡", "℟", "ᴮ", "ᴼ", "ᴛᴇᴀᴍ",
    "cs.deals","twat", "< blank >", "STRESS.PW"
}


---# Blacklist Events #---
DELTAX.BlacklistetEvents = true

DELTAX.Events = {
    "mellotrainer:adminKick",
        'antilynx8:anticheat',
        'antilynxr4:detect',
        'antilynxr6:detection',
        "HCheat:TempDisableDetection",
        'ynx8:anticheat',
        'antilynx8r4a:anticheat',
        'lynx8:anticheat',
        'AntiLynxR4:kick',
        'esx_spectate:kick',
        'AntiLynxR4:log',
        'chat:server:ServerPSA',
        'd0pamine_xyz:getFuckedNigger',
        'adminmenu:allowall',
        'esx_mafiajob:confiscatePlayerItem',
        'NB:recruterplayer',
        ':tunnel_req',
        'f0ba1292-b68d-4d95-8823-6230cdf282b6',
        'gambling:spend',
        'hentailover:xdlol',
        'OG_cuffs:cuffCheckNearest',
        'hentailover:xdlol',
        'display',
        'advancedFuel:setEssence',
        'esx:jackingcar',
		'esx-qalle-jail:jailPlayer',		--ESX-QALLE-JAIL
		'esx_vangelico_robbery:gioielli', -- JUWELIER
        'quallemeinemutter:fickdasflyteam', -- Qalle Jail
         'lester:vendita', -- JUWELIER
        'phase_oocchat:ooc', -- OOC-Chat
       'KorioZ-PersonalMenu:Admin_giveCash', -- Givemoney
       'KorioZ-PersonalMenu:Admin_giveBank', -- Givebank
       'KorioZ-PersonalMenu:Admin_giveDirtyMoney', -- Dirtymoney
	   'esx_ambulancejob:revive', -- Ambulancerevive
	   'esx-qalle-jail:openJailMenu', -- Qalle Jail
        'bringplayertome', -- Bring player to me Aduty
        'fuel:pay', -- Tankstelle
       'bens_cuff_item:handcuff',
  }
  
  ---# Anti Nuke #---
  DELTAX.AntiNuke = true

  DELTAX.NukeResetTime = 10000
  
  DELTAX.MaxVehicles = 2

  DELTAX.MaxPeds = 2

 ---# Anti Particles #---
  DELTAX.AntiParticles = true

  DELTAX.ParticelResetTime = 5000

  DELTAX.MaxParticles = 3


  ---# Anti Blacklist Entity #---
  DELTAX.BlacklistEntity = true

  ---# Anti Invisible Entity #---
  DELTAX.AntiInvisibleEntity = false
  
  DELTAX.Entity = {
  
  	"cargoplane",
	"tug",
	"prop_xmas_tree_int",
	"xm_prop_x17_xmas_tree_int",
	"xs3_prop_int_xmas_tree_01",
	"xs_propintxmas_tree_2018",
	"02gate3_l",
	"tampa2",
	"a_m_m_hasjew_01",
	"prop_container_01a",
	'dt1_05_build1_damage',
	"dt1_05_build1_damage_lod",
	"a_m_o_acult_01",
	"a_c_sharkhammer",
"prop_container_01b",
"prop_gas_tank_01a",
"ig_claypain",
"buzzard",
"dubsta3",
"veto2",
"apa_mp_h_acc_rugwoolm_03",
"prop_parking_hut_2",
"prop_parking_hut_2b",
"ch_prop_parking_hut_2",
"dt1_21_parkinghut",
"veto",
"prop_gascyl_01a",
"prop_cs_dildo_01",
"prop_ld_toilet_01",
"prop_ld_bomb_anim",
"prop_ld_farm_couch01",
"-759902142",
"g_m_m_chemwork_01",
	"u_m_y_babyd",
	"u_m_y_pogo_01",
	"s_m_m_movalien_01",
	"a_c_chimp",
    "prop_dog_cage_01",
    "prop_dog_cage_02",
	"s_f_y_stripper_01",
	"s_m_y_clown_01",
	"a_m_m_hasjew_01",
	"a_m_m_acult_01",
	"a_m_y_mexthug_01", 
"-1404869155",
"stromberg",
"prop_doghouse_01",
"prop_contnr_pile_01a",
"ce_xr_ctr2",
"stt_prop_stunt_track_start",
"-145066854",
"prop_container_05a",
"prop_med_jet_01",
"prop_vintage_pump",
"prop_container_01c",
"prop_container_01d",
"prop_container_01e",
"prop_container_01f",
"prop_container_01g",
"prop_container_01h",
"prop_container_01mb",
"prop_container_02a",
"prop_container_03a",
"prop_container_03b",
"prop_container_03mb",
"prop_container_03_ld",
"prop_container_04a",
"prop_container_04mb",
"prop_container_05mb",
"prop_container_door_mb_l",
"prop_container_door_mb_r",
"prop_container_hole",
"prop_container_ld",
"prop_container_ld2",
"prop_container_old1",
"prop_dog_cage_01",
"prop_dog_cage_02",
"prop_weed_01",
	"prop_fnclink_05crnr1",
	"xs_prop_hamburgher_wl",
	"xs_prop_plastic_bottle_wl",
	"prop_windmill_01",
	"p_spinning_anus_s",
	"stt_prop_ramp_adj_flip_m",
	"stt_prop_ramp_adj_flip_mb",
	"stt_prop_ramp_adj_flip_s",
	"stt_prop_ramp_adj_flip_sb",
	"stt_prop_ramp_adj_hloop",
	"stt_prop_ramp_adj_loop",
	"stt_prop_ramp_jump_l",
	"stt_prop_ramp_jump_m",
	"stt_prop_ramp_jump_s",
	"stt_prop_ramp_jump_xl",
	"stt_prop_ramp_jump_xs",
	"stt_prop_ramp_jump_xxl",
	"hei_prop_carrier_jet",
	"csx_seabed_rock3_",
	    "db_apart_09_",
    "stt_prop_stunt_tube_l",
	"prop_parking_hut_2",
    "stt_prop_stunt_track_dwuturn",
	"prop_atm_01",
	"prop_box_wood06a",
	"prop_juicestand",
	"p_ferris_wheel_amo_l2",
    "sr_prop_spec_tube_xxs_01a",
	"prop_air_bigradar",
	"p_tram_crash_s",
	"prop_windmill_01",
	"prop_start_gate_01",
	"prop_trailer_01_new",
	"sr_prop_sr_track_block_01",
	"sr_prop_spec_tube_xxs_04a",
	"v_ilev_gc_weapons",
	"stt_prop_stunt_soccer_sball",
	"stt_prop_stunt_track_cutout",
	"stt_prop_stunt_target_small",
	"prop_cj_big_boat",
	"stt_prop_ramp_multi_loop_rb",
	"stt_prop_ramp_spiral_l",
	"stt_prop_ramp_spiral_l_l",
	"stt_prop_ramp_spiral_l_m",
	"stt_prop_ramp_spiral_l_s",
	"stt_prop_ramp_spiral_l_xxl",
	"stt_prop_ramp_spiral_m",
	"stt_prop_ramp_spiral_s",
	"stt_prop_ramp_spiral_xxl",
    "prop_beach_fire",
    "prop_rock_1_a",
    "prop_rock_1_b",
    "prop_rock_1_c",
    "prop_rock_1_d",
    "prop_player_gasmask",
    "prop_rock_1_g",
    "prop_rock_1_h",
    "prop_test_boulder_01",
    "prop_test_boulder_02",
    "prop_test_boulder_03",
    "prop_test_boulder_04",
    "apa_mp_apa_crashed_usaf_01a",
    "ex_prop_exec_crashdp",
    "apa_mp_apa_yacht_o1_rail_a",
    "apa_mp_apa_yacht_o1_rail_b",
    "apa_mp_h_yacht_armchair_01",
    "apa_mp_h_yacht_armchair_03",
    "apa_mp_h_yacht_armchair_04",
    "apa_mp_h_yacht_barstool_01",
    "apa_mp_h_yacht_bed_01",
    "apa_mp_h_yacht_bed_02",
    "apa_mp_h_yacht_coffee_table_01",
    "apa_mp_h_yacht_coffee_table_02",
    "apa_mp_h_yacht_floor_lamp_01",
    "apa_mp_h_yacht_side_table_01",
    "apa_mp_h_yacht_side_table_02",
    "apa_mp_h_yacht_sofa_01",
    "apa_mp_h_yacht_sofa_02",
    "apa_mp_h_yacht_stool_01",
    "apa_mp_h_yacht_strip_chair_01",
    "apa_mp_h_yacht_table_lamp_01",
    "apa_mp_h_yacht_table_lamp_02",
    "apa_mp_h_yacht_table_lamp_03",
    "prop_flag_columbia",
    "apa_mp_apa_yacht_o2_rail_a",
    "apa_mp_apa_yacht_o2_rail_b",
    "apa_mp_apa_yacht_o3_rail_a",
    "apa_mp_apa_yacht_o3_rail_b",
    "apa_mp_apa_yacht_option1",
    "proc_searock_01",
    "apa_mp_h_yacht_",
    "apa_mp_apa_yacht_option1_cola",
    "apa_mp_apa_yacht_option2",
    "apa_mp_apa_yacht_option2_cola",
    "apa_mp_apa_yacht_option2_colb",
    "apa_mp_apa_yacht_option3",
    "apa_mp_apa_yacht_option3_cola",
    "apa_mp_apa_yacht_option3_colb",
    "apa_mp_apa_yacht_option3_colc",
    "apa_mp_apa_yacht_option3_cold",
    "apa_mp_apa_yacht_option3_cole",
    "apa_mp_apa_yacht_jacuzzi_cam",
    "apa_mp_apa_yacht_jacuzzi_ripple003",
    "apa_mp_apa_yacht_jacuzzi_ripple1",
    "apa_mp_apa_yacht_jacuzzi_ripple2",
    "apa_mp_apa_yacht_radar_01a",
    "apa_mp_apa_yacht_win",
    "prop_crashed_heli",
    "apa_mp_apa_yacht_door",
    "prop_shamal_crash",
    "xm_prop_x17_shamal_crash",
    "apa_mp_apa_yacht_door2",
    "apa_mp_apa_yacht",
    "apa_prop_yacht_glass_06",
    "apa_prop_yacht_glass_07",
    "apa_prop_yacht_glass_08",
    "apa_prop_yacht_glass_09",
    "apa_prop_yacht_glass_10",
    "prop_flag_canada_s",
    "prop_flag_eu",
    "prop_flag_eu_s",
    "prop_target_blue_arrow",
    "prop_target_orange_arrow",
    "prop_target_purp_arrow",
    "prop_target_red_arrow",
    "prop_aircon_l_03",
    "csx_coastsmalrock_05_",
    "mp_player_int_rock",
    "mp_player_introck",
    "prop_flagpole_1a",
    "prop_flagpole_2a",
    "prop_flagpole_3a",
    "prop_a4_pile_01",
    "cs2_10_sea_rocks_lod",
    "cs2_11_sea_marina_xr_rocks_03_lod",
    "prop_gold_cont_01",
    "prop_hydro_platform",
    "ch3_04_viewplatform_slod",
    "ch2_03c_rnchstones_lod",
    "proc_mntn_stone01",
    "prop_beachflag_le",
	"stt_prop_stunt_track_uturn",
	"stt_prop_stunt_track_turnice",
	"stt_prop_stunt_track_hill",
    "proc_mntn_stone02",
    "cs2_10_sea_shipwreck_lod",
    "des_shipsink_02",
    "csx_coastboulder_00",
    "des_tankercrash_01",
    "des_tankerexplosion_01",
    "des_tankerexplosion_02",
    "des_trailerparka_02",
    "des_traincrash_root7",
    "ch2_03c_props_rrlwindmill_lod",
    "prop_flamingo",
    "prop_asteroid_01",
	"stt_prop_stunt_soccer_ball",
    "stt_prop_stunt_bowling_ball",
    "stt_prop_stunt_bowling_pin",
	"a_m_y_acult_01",
	"a_m_o_acult_02",
    "stt_prop_stunt_soccer_ball",
    "stt_prop_stunt_soccer_lball",
    "stt_prop_stunt_soccer_sball",
    "stt_prop_stunt_tube_fn_01",
    "stt_prop_stunt_tube_fn_02",
    "stt_prop_stunt_tube_fn_03",
    "stt_prop_stunt_tube_fn_04",
    "stt_prop_stunt_tube_fn_05",
    "stt_prop_stunt_domino",
	"a_c_boar",
	"a_c_killerwhale",
	"a_m_y_acult_02",
	"db_apart_03_",
    "db_apart_09_",
    "csb_stripper_01",
	"a_c_sharktiger",
    "stt_prop_stunt_jump15",
    "stt_prop_stunt_jump30",
    "stt_prop_stunt_jump45",
    "stt_prop_stunt_jump_l",
    "stt_prop_stunt_jump_lb",
    "stt_prop_stunt_jump_loop",
    "stt_prop_stunt_jump_m",
    "stt_prop_stunt_jump_mb",
    "stt_prop_stunt_jump_s",
    "stt_prop_stunt_jump_sb",
    "stt_prop_stunt_landing_zone_01",
    "stt_prop_stunt_ramp",
    "stt_prop_stunt_target",
    "stt_prop_stunt_target_small",
    "stt_prop_stunt_target",
    "stt_prop_stunt_track_bumps",
    "stt_prop_stunt_track_cutout",
    "stt_prop_stunt_track_dwlink",
    "stt_prop_stunt_track_dwlink_02",
    "stt_prop_stunt_track_dwsh15",
    "stt_prop_stunt_track_dwshort",
    "stt_prop_stunt_track_dwslope15",
    "stt_prop_stunt_track_dwslope30",
    "stt_prop_stunt_soccer_goal",
    "stt_prop_stunt_tube_jmp2",
    "stt_prop_track_stop_sign",
    "stt_prop_race_gantry_01",
    "stt_prop_race_start_line_01",
    "stt_prop_race_start_line_01b",
    "stt_prop_race_start_line_02",
    "stt_prop_race_start_line_02b",
    "stt_prop_race_start_line_03",
    "stt_prop_race_start_line_03b",
    "stt_prop_race_tannoy",
    "stt_prop_ramp_adj_flip_m",
    "stt_prop_ramp_adj_flip_mb",
    "stt_prop_ramp_adj_flip_s",
    "stt_prop_ramp_adj_flip_sb",
    "stt_prop_ramp_adj_hloop",
    "stt_prop_ramp_adj_loop",
    "stt_prop_ramp_jump_l",
    "stt_prop_ramp_jump_m",
    "stt_prop_ramp_jump_s",
    "stt_prop_ramp_jump_xl",
    "stt_prop_ramp_jump_xs",
    "stt_prop_ramp_jump_xxl",
    "stt_prop_ramp_multi_loop_rb",
    "stt_prop_ramp_spiral_l",
    "stt_prop_ramp_spiral_l_l",
    "stt_prop_ramp_spiral_l_m",
    "stt_prop_ramp_spiral_l_s",
    "stt_prop_ramp_spiral_l_xxl",
    "stt_prop_ramp_spiral_m",
    "stt_prop_ramp_spiral_s",
    "stt_prop_ramp_spiral_xxl",
    "p_crahsed_heli_s",
    "prop_rock_4_big2",
    "prop_beachflag_le",
    "xs_prop_hamburgher_wl",
		"khanjali",
    "rhino",
    "scarab2",	 
    "scarab3",	
	"cablecar",
    "scarab",	
    "trailersmall2",	
    "minitank",	
    "scarab2",	
	"valkyrie",
	"Cerberus",
	"blimp3",
	"blimp4",
	"blimp5",
	"hydra",
	"lazer",
	"savage",
	"Hunter",
	"Oppressor",
	"blimp2",
	"avenger",
	"bombushka",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"docktrailer",
	"freighttrailer",
	"graintrailer",
	"roptrailer",
	"tr2",
	"tr4",
	"trflat",
	"tvtrailer",
	"tanker",
	"tanker2",
	"trailerlarge",
	"trailerlogs",
	"trailersmall",
	"trailers",
	"trailers3",
	"trailers4",
	"freightcar",
	"freight",
	"freightcont1",
	"freightcont2",
	"reightgrain",
	"metrotrain",
	"tankercar",
	"thruster",
	"bulldozer",
	"cutter",
	"dump",
	"handler",
	"apc",
	"chernobog",	
	"trailers4",
	"molotok",
	"caracara",
	"pyro",
	"nokota",
	"nightshark",
	"monster",
	"vigilante",
	"menacer",
	"nightshark",
	"rcbandito",
	"technical",
	"technical2",
	"technical3",
	"rrocket",
	"dominator6",
	"ruiner2",
	"ruiner3",
	"slamvan6",
	"tampa3",
	"bruiser3",
	"brutus3",
	"caracara",
	"dune2",
	"dune3",
	"dune4",
	"dune5",
	"insurgent",
	"insurgent3",
	"monster5",
	"menacer",
	"nightshark",
		"barrage",
		"patrolboat",
	"phantom2",
	"akula",
	"annihilator",
    "sr_prop_spec_tube_xxs_01a"
  
  
  
  }

  DELTAX.Explosionlist = {
    [0] = { name = "Grenade", log = true, ban = true },
    [1] = { name = "GrenadeLauncher", log = true, ban = true },
    [3] = { name = "Molotov", log = true, ban = true },
    [4] = { name = "Rocket", log = true, ban = true },
    [5] = { name = "TankShell", log = true, ban = true},
    [6] = { name = "Hi_Octane", log = false, ban = false },
    [7] = { name = "Car", log = false, ban = false },
    [8] = { name = "Plance", log = false, ban = false },
    [9] = { name = "PetrolPump", log = false, ban = false },
    [10] = { name = "Bike", log = false, ban = false },
    [11] = { name = "Dir_Steam", log = false, ban = false },
    [12] = { name = "Dir_Flame", log = false, ban = false },
    [13] = { name = "Dir_Water_Hydrant", log = false, ban = false },
    [14] = { name = "Dir_Gas_Canister", log = false, ban = false },
    [15] = { name = "Boat", log = false, ban = false },
    [16] = { name = "Ship_Destroy", log = false, ban = false },
    [17] = { name = "Truck", log = false, ban = false },
    [18] = { name = "Bullet", log = true, ban = true },
    [19] = { name = "SmokeGrenadeLauncher", log = true, ban = true },
    [20] = { name = "SmokeGrenade", log = false, ban = false },
    [21] = { name = "BZGAS", log = false, ban = false },
    [22] = { name = "Flare", log = false, ban = false },
    [23] = { name = "Gas_Canister", log = false, ban = false },
    [24] = { name = "Extinguisher", log = false, ban = false },
    [25] = { name = "Programmablear", ban = false },
    [26] = { name = "Train", log = false, ban = false },
    [27] = { name = "Barrel", log = false, ban = false },
    [28] = { name = "PROPANE", log = false, ban = false },
    [29] = { name = "Blimp", log = false, ban = false },
    [30] = { name = "Dir_Flame_Explode", log = false, ban = false },
    [31] = { name = "Tanker", log = false, ban = false },
    [32] = { name = "PlaneRocket", log = true, ban = true },
    [33] = { name = "VehicleBullet", ban = false },
    [34] = { name = "Gas_Tank", log = true, ban = true },
    [35] = { name = "FireWork", log = false, ban = false },
    [36] = { name = "SnowBall", log = false, ban = false },
    [37] = { name = "GAS_TANK", log = true, ban = true },
    [38] = { name = "Valkyrie_Cannon", log = true, ban = true }
}